# Generated by Django 5.0.1 on 2024-01-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientappointment', '0002_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(choices=[('09:00', '9:00 AM'), ('09:20', '9:20 AM'), ('09:40', '9:40 AM'), ('10:00', '10:00 AM'), ('10:20', '10:20 AM'), ('10:40', '10:40 AM'), ('11:00', '11:00 AM'), ('11:20', '11:20 AM'), ('11:40', '11:40 AM'), ('12:00', '12:00 PM'), ('12:20', '12:20 PM'), ('12:40', '12:40 PM'), ('13:00', '1:00 PM'), ('13:20', '1:20 PM'), ('13:40', '1:40 PM'), ('14:00', '2:00 PM')], default='09:00', max_length=50),
        ),
    ]
